audit:
  - [_FIELD_]
  - [source]
  - [ean]
  - [brand]
  - [brand, product]
  - [width, series, rim]
fs:
  data_directory: data
  log_directory: public/data/log
mdm:
  source_system_key: source
  unique_keys:
    - [ean]
    - [brand, manufacturer_number]
  timestamp_key: crawled
steps:
  import:
    keys:
      - [source,id]
    source_system_key: source
    rules:
      ## remove strange_characterts at the begin
      - filter:
          keys: /^[\s'"]+/i
        action:
          command: keys_replace
          param1: ''
      ## remove strange_characterts at the end
      - filter:
          keys: /[\s'"]+$/i
        action:
          command: keys_replace
          param1: ''
      ## remove strange_characterts at the begin
      - filter:
          values: /^[\s'"]+/i
        action:
          command: values_replace
          param1: ''
      ## remove strange_characterts at the end
      - filter:
          values: /[\s'"]+$/i
        action:
          command: values_replace
          param1: ''
        ## remove strange_characterts anywhere
      - filter:
          values: /['"\(\)\n\r]+/i
        action:
          command: values_replace
          param1: ''
      - filter:
          values: /^sì|si|yes$/i
        action:
          command: values_replace
          param1: true
      - filter:
          values: /^sno$/i
        action:
          command: values_replace
          param1: false
      - filter:
          values: /^\s*$/i
        action:
          command: values_replace
          param1: null
      - filter:
        action:
          command: keys_to_lowercase
          param1:
      - filter:
          keys: /^Hersteller$/i
        action:
          command: keys_replace
          param1: brand
      - filter:
          keys: /^ArtikelBezeichnung$/i
        action:
          command: keys_replace
          param1: description
      - filter:
          keys: /^Preis$/i
        action:
          command: keys_replace
          param1: price
      - filter:
          keys: /^profil$/i
        action:
          command: keys_replace
          param1: product
      - filter:
          keys: /^reifenbreite|larghezza$/i
        action:
          command: keys_replace
          param1: width
      - filter:
          keys: /^querschnitt|altezza$/i
        action:
          command: keys_replace
          param1: series
      - filter:
          keys: /^ReifenDurchmesser|diametro|diameter$/i
        action:
          command: keys_replace
          param1: rim
      - filter:
          keys: /^valuta|Waehrung|währung$/i
        action:
          command: keys_replace
          param1: currency
      - filter:
          keys: /^Speedindex$/i
        action:
          command: keys_replace
          param1: speed_index
      - filter:
          keys: /^Loadindex$/i
        action:
          command: keys_replace
          param1: load_index
      - filter:
          keys: /^Warengruppe1$/i
        action:
          command: keys_replace
          param1: seasonality
      - filter:
          keys: /^EANCode$/i
        action:
          command: keys_replace
          param1: ean
      - filter:
          keys: /^(Kraftstoffeffizienzklasse|taloudellisuus|labelfuel|label fuel)$/i
        action:
          command: keys_replace
          param1: label_fuel
      - filter:
          keys: /^vierintämelu|ExternesRollgeraeusch$/i
        action:
          command: keys_replace
          param1: label_noise
      - filter:
          keys: /^märkäpito|Nasshaftungsklasse$/i
        action:
          command: keys_replace
          param1: label_wet
      - filter:
          keys: /^indice di velocità$/i
        action:
          command: keys_replace
          param1: speed_index
      - filter:
          keys: /^indice di portanza$/i
        action:
          command: keys_replace
          param1: load_index
      - filter:
          keys: /^stagione|season$/i
        action:
          command: keys_replace
          param1: seasonality
      - filter:
          keys: /^tipo|type$/i
        action:
          command: keys_replace
          param1: vehicle
      - filter:
          keys: /^(protezione del cerchio)|(bordo di protezione)$/i
        action:
          command: keys_replace
          param1: mfs
      - filter:
          keys: /^pneumatici runflat$/i
        action:
          command: keys_replace
          param1: runflat
      - filter:
          keys: /^pneumatici chiodati$/i
        action:
          command: keys_replace
          param1: studded
      - filter:
          keys: /^ArtikelNr$/i
        action:
          command: keys_replace
          param1: id
      - filter:
          keys: /brand|product|description|size|vehicle|seasonality|label_fuel|label_noise|label_wet|type|speed_index/i
          values:
        action:
          command: values_to_uppercase
          param1:
  append:
      keys:
        - [ean]
        - [brand, manufacturer_number]
      rules:
        - filter:
            values: /^(si|yes|true)$/i
          action:
            command: values_replace
            param1: true
        - filter:
            values: /^(no|false)$/i
          action:
            command: values_replace
            param1: false
        - filter:
            values: /^null$/i
          action:
            command: values_replace
            param1: null
        - filter:
            keys: /^brand$/i
            values: /[-_]/i
          action:
            command: values_replace
            param1: ' '
        - filter:
            keys: /^label_noise$/i
            values: / ?db$/i
          action:
            command: values_replace
            param1: ''
        - filter:
            keys: /^seasonality$/i
            values: /WINTER|INVERNAL|M\+S|SNOW|KITKARENGAS|NASTARENGAS|Zimné/i
          action:
            command: values_replace
            param1: WINTER
            param2: true # replace_all string
        - filter:
            keys: /^seasonality$/i
            values: /SUMMER|ESTIV|KESÄRENGAS|Letné/i
          action:
            command: values_replace
            param1: SUMMER
            param2: true # replace_all string
        - filter:
            keys: /^seasonality$/i
            values: /SEASON|STAGIONI|4MEVSIM|JOKASÄÄNRENGAS|Celoročné/i
          action:
            command: values_replace
            param1: SUMMER
            param2: true # replace_all string
        - filter:
            keys: /^vehicle$/i
            values: /^auto|PKW|PA$/i
          action:
            command: values_replace
            param1: CAR
        - filter:
            keys: /^vehicle$/i
            values: /^HA$/i
          action:
            command: values_replace
            param1: VAN
        - filter:
            keys: /^vehicle$/i
            values: /^4x4|OFF[- ]?ROAD|SUV/i
          action:
            command: values_replace
            param1: SUV
        - filter:
            keys: /^url|ProduktURL|test|ArtBez2|Zusatz|Testurteil|Medium|Ausgabe|Stueckzahl|Preisinfo|MwSt|Versandkosten|Zahlarten|HinweisFinanzierung|Lieferzeit|Versender|Warengruppe2|Preiskategorie|Bestellinfo/i
          action:
            command: keys_delete
            param1:
        - filter:
            keys: /^description$/i
            values: /front/i
          action:
            command: key_add
            param1: front_rear
            param2: front
        - filter:
            keys: /^description$/i
            values: /rear/i
          action:
            command: key_add
            param1: front_rear
            param2: rear
        - filter:
            keys: /^description$/i
            values: / (MFS|FSL|PROTEZIONE|FRP?)/i
          action:
            command: key_add
            param1: mfs
            param2: true
        - filter:
            keys: /^description$/i
            values: / (DSST|EMT|HRFS|MOExtended|PAX|RUNFLAT|R-F|RFT|ROF|SSR|(RUN FLAT)|TRF|ZRP|ZP|ZPS)/i
          action:
            command: key_add
            param1: runflat
            param2: true
        - filter:
            keys: /^description$/i
            values: / (SIL|ACO|ACOUSTIC|NST|SOUND|SILENT)/i
          action:
            command: key_add
            param1: ncs
            param2: true
        - filter:
            keys: /^description$/i
            values: /winter/i
          action:
            command: key_add
            param1: seasonality
            param2: WINTER
        - filter:
            keys: /^description$/i
            values: / (s-i|sealing|cs)/i
          action:
            command: key_add
            param1: seal_inside
            param2: true
        - filter:
            keys: /^description$/i
            values: / XL/i
          action:
            command: key_add
            param1: extra_load
            param2: true
        - filter:
            keys: /^description$/i
            values: /studded|chiodat|NASTARENGAS|SPIKE/i
          action:
            command: key_add
            param1: studded
            param2: true
        - filter:
            keys: /^description$/i
            values: /studdable|chiodabil/i
          action:
            command: key_add
            param1: studdable
            param2: true
        - filter:
            keys: /^price$/i
            values: /\$/i
          action:
            command: key_add
            param1: currency
            param2: USD
        - filter:
            keys: /^price$/i
            values: /€/i
          action:
            command: key_add
            param1: currency
            param2: EUR
  merge:
      keys:
        - [ean]
  export:
      keys:
        - [ean]
      fields:
        ean: [string]
        brand: [string]
        crawled: [string, multivalue]
        currency: [string, multivalue]
        description: [string, multivalue]
        extra: [string, multivalue]
        extra_load: [string]
        front_rear: [string]
        label_fuel: [string]
        label_noise: [string]
        label_wet: [string]
        load_index: [string]
        logging: [string, multivalue]
        manufacturer_number: [string]
        mfs: [string]
        oe_marks: [string, multivalue]
        price: [string, multivalue]
        product: [string, multivalue]
        rim: [string]
        runflat: [bool]
        seal_inside: [string]
        seasonality: [string]
        series: [string]
        source: [string, multivalue]
        speed_index: [string]
        studdable: [string]
        studded: [string]
        vehicle: [string, multivalue]
        width: [string]
