db:
  host: localhost:9200
  log: trace
  index: mdm
fs:
  data_directory: public/data
  document_keys_file: keys.yaml
  document_values_file: values.yaml
steps:
  import:
    keys: [source,id]
    rules:
      ## remove strange_characterts at the begin
      - filter:
          keys: /^[\s'"]+/i
        action:
          command: keys_replace
          param1: ''
      ## remove strange_characterts at the end
      - filter:
          keys: /[\s'"]+$/i
        action:
          command: keys_replace
          param1: ''
      ## remove strange_characterts at the begin
      - filter:
          values: /^[\s'"]+/i
        action:
          command: values_replace
          param1: ''
      ## remove strange_characterts at the end
      - filter:
          values: /[\s'"]+$/i
        action:
          command: values_replace
          param1: ''
      - filter:
        action:
          command: keys_to_lowercase
          param1:
      - filter:
          keys: /brand|product|description|size|vehicle|seasonality|label_fuel|label_noise|label_wet/i
          values:
        action:
          command: values_to_uppercase
          param1:
      - filter:
          keys: /^taloudellisuus$/i
        action:
          command: keys_replace
          param1: label_fuel
      - filter:
          keys: /^(labelfuel|label fuel)$/i
        action:
          command: keys_replace
          param1: label_fuel
      - filter:
          keys: /^vierintämelu$/i
        action:
          command: keys_replace
          param1: label_noise
      - filter:
          keys: /^märkäpito$/i
        action:
          command: keys_replace
          param1: label_wet
  export:
      unique_keys:
        - [ean]
        - [brand, manufacturer_number]
      rules:
        - filter:
            values: /^(si|yes|true)$/i
          action:
            command: values_replace
            param1: true
        - filter:
            values: /^(no|false)$/i
          action:
            command: values_replace
            param1: false
        - filter:
            keys: /^brand$/i
            values: /[-_]/i
          action:
            command: values_replace
            param1: ' '
        - filter:
            keys: /^url|test$/i
          action:
            command: keys_delete
            param1:
        - filter:
            keys: /^description$/i
            values: /runflat/i
          action:
            command: key_add
            param1: runflat
            param2: true
            #param3: true
