fs:
  import: public/data/import
  work: public/data/work
  export: public/data
  keys_file: public/data/keys.yaml
  values_file: public/data/values.yaml
document:
  import_keys:
    id_key: id
    source_key: source
  export_key: ean
  constaints:
    required:
      - brand
      - manufacturer_number
      - product
      - width
      - height
      - rim
      - season
    sufficient:
      - [brand, manufacturer_number]
normalizer:
  import:
    - filter:
      ##keys: []
      ##values: []
      action:
        command: keys_to_lowercase
        param1:
    - filter:
      keys: []
      values: []
      action:
        command: values_to_uppercase
        param1:
  export:
    - filter:
      action:
        command: normalize_keys
        param1:
