db:
  host: localhost:9200
  log: trace
  index: mdm
fs:
  data_directory: public/data
  document_keys_file: keys.yaml
  document_values_file: values.yaml
steps:
  import:
    keys: [source,id]
    rules:
      - filter:
        ##keys: []
        ##values: []
        action:
          command: keys_with_only_letters_numbers_and_underscores2
          param1:
      - filter:
        action:
          command: keys_to_lowercase
          param1:
      - filter:
          keys: [brand, product, size]
          values:
        action:
          command: values_to_uppercase
          param1:
  export:
      unique_keys:
        - [ean]
        - [brand, manufacturer_number]
      rules:
        - filter:
          action:
            command: normalize_keys
            param1:
